# Generated by Django 5.2.5 on 2025-10-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rental_period',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM (e.g., 2025-10)', max_length=20),
        ),
    ]
