# Generated by Django 5.2.5 on 2025-10-18 16:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='property',
            new_name='tenant_property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rent_due_date',
        ),
    ]