# Generated by Django 5.2.5 on 2025-10-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_number', models.CharField(max_length=20, unique=True)),
                ('rental_type', models.CharField(choices=[('SINGLE_ROOM', 'Single Room'), ('DOUBLE_ROOM', 'Double Room'), ('SHOP', 'Shop'), ('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio')], max_length=50)),
                ('monthly_rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
