# Generated by Django 5.2.7 on 2025-10-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
