# Generated by Django 5.2.7 on 2025-10-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_rental_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='tenant',
        ),
    ]
